[project]
drom-version = "0.1"
share-repo = "https://github.com/OCamlPro/drom-share"
share-version = "0.9.2"

[project]
authors = ["Steven de Oliveira <steven.de-oliveira@ocamlpro.com>", "Nicolas Berthier <nicolas.berthier@ocamlpro.com>"]
bug-reports = "https://gitlab.ocamlpro.com/OCamlPro/seacoral/-/issues"
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "OCamlPro"
edition = "4.14.1"
homepage = "https://ocamlpro.com/seacoral"
license = "GPL3"
min-edition = "4.14.0"
name = "seacoral"
skeleton = "program"
synopsis = "Collaborative Test Generation Toolset for C"
# Note: we use git tags to define the version in the tool. This
# particular field is only used when generating opam package files.
version = "1.1~dev"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# github-organization = "...github-organization..."

[project]
description = """
SeaCoral is an orchestration tool that is able to combine the power of
a wide range of test generation techniques in order to automatically
produce tests for your C projects.
"""

[project]
skip = [
  "test",
  "test/output-tests/dune",
  "test/output-tests/test1.ml", "test/output-tests/test1.expected",
  "test/output-tests/test2.ml", "test/output-tests/test2.expected",
  "test/inline-tests/dune",
  "test/inline-tests/test.ml",
  "test/expect-tests/dune",
  "test/expect-tests/test.ml",
  "sphinx/index.rst",
  ".github/workflows/workflow.yml"
]

# project-wide library dependencies (not for package-specific deps)
[dependencies]
fmt = ">=0.9.0"
[dependencies.lwt]
libname = "lwt.unix"

# project-wide tools dependencies (not for package-specific deps)
[tools]
dune = ">=3.14"
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
# examples:
#  docker-alpine-image = "ocamlpro/ocaml:4.13"
#  dune-lang = "2.1"
#  readme-trailer = "..."
#  dot-gitignore-trailer = "..."
[fields]
dune = "3.14.0"
dot-gitignore-trailer = """
*.mdl
.envrc
"""
readme-trailer = """
## Running SeaCoral in a Docker container

Instructions for using SeaCoral in a Docker container are provided [in
the `docker` subdirectory](docker/README.md).
"""

[[package]]
dir = "src/seacoral"
# edit 'src/seacoral/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-lib"
# edit 'src/seacoral-lib/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-klee"
# edit 'src/seacoral-klee/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-ltest"
# edit 'src/seacoral-ltest/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-fuzz"
# edit 'src/seacoral-fuzz/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-main"
# edit 'src/seacoral-main/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-store"
# edit 'src/seacoral-store/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-cbmc"
# edit 'src/seacoral-cbmc/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-report"
# edit 'src/seacoral-report/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-project"
# edit 'src/seacoral-project/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-replayer"
# edit 'src/seacoral-replayer/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-sys"
# edit 'src/seacoral-sys/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-basics"
# edit 'src/seacoral-basics/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-c"
# edit 'src/seacoral-c/package.toml' for package-specific options

[[package]]
dir = "src/ez-logs"
# edit 'src/ez-logs/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-values"
# edit 'src/seacoral-values/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-crunch"
# edit 'src/seacoral-crunch/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-config"
# edit 'src/seacoral-config/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-strategy"
# edit 'src/seacoral-strategy/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-core"
# edit 'src/seacoral-core/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-luncov"
# edit 'src/seacoral-luncov/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-corpus"
# edit 'src/seacoral-corpus/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-cil-shims"
# edit 'src/seacoral-cil-shims/package.toml' for package-specific options

[[package]]
dir = "src/seacoral-postproc"
# edit 'src/seacoral-postproc/package.toml' for package-specific options

